# fly.toml app configuration file generated for jasperserver on 2025-11-08T17:18:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jasperserver'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  DB_HOST = 'jasperserver-db.fly.dev'
  DB_PORT = '5432'
  DB_TYPE = 'postgresql'
  DB_USER = 'postgres'
# DB_NAME = 'jasperserver'
# DB_PASSWORD = '******'
#
# fly secrets set DB_PASSWORD="******"
# fly ssh console -C "printenv"

[[mounts]]
  source = 'jasper_webapps_dir'
  destination = '/usr/local/tomcat/webapps'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
