# fly.toml app configuration file generated for jasperserver on 2025-11-05T21:26:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jasperserver'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile.fly'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
    DB_HOST = 'jasperserver-db.flycast'
    DB_PORT = '5432'
    DB_USER = 'postgres'
    DB_DB_NAME = 'jasperserver'
    DB_TYPE = 'postgresql'
#   DB_PASSWORD = 'password1234'
	
# fly secrets set SUPER_SECRET_KEY=password1234
# fly ssh console -C "printenv"
