# fly.toml app configuration file generated for jasperserver-db on 2025-11-07T12:35:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jasperserver-db'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'pg_data'
  destination = '/var/lib/postgresql'

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 5432
    handlers = ['pg_tls']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
